[build]
builder = "dockerfile"
dockerfilePath = "./worker/Dockerfile.railway"

[deploy]
startCommand = "rq worker -u $REDIS_URL main --with-scheduler"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

