[build]
builder = "dockerfile"
dockerfilePath = "./worker/Dockerfile.railway"

[deploy]
startCommand = "sh -c 'rq worker -u $REDIS_URL main --with-scheduler'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

