#!/bin/bash

# Okuma Analizi - Mobile Access Starter
# Bu script otomatik olarak IP adresinizi algılar ve sistemi başlatır

echo "🚀 Okuma Analizi - Mobil Erişim Başlatıcı"
echo "========================================"
echo ""

# IP adresini algıla
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    HOST_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)
    if [ -z "$HOST_IP" ]; then
        echo "⚠️  WiFi bağlantısı bulunamadı!"
        echo "Ethernet veya başka bir ağ bağlantısı kullanıyor olabilirsiniz."
        echo ""
        echo "Mevcut IP adresleri:"
        ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print "  - " $2}'
        echo ""
        read -p "Kullanmak istediğiniz IP adresini girin: " HOST_IP
    fi
else
    # Linux
    HOST_IP=$(hostname -I | awk '{print $1}')
fi

if [ -z "$HOST_IP" ]; then
    echo "❌ IP adresi algılanamadı!"
    exit 1
fi

echo "✅ IP Adresi: $HOST_IP"
echo ""

# .env.local dosyasını güncelle
echo "📝 Frontend .env.local dosyası güncelleniyor..."
cat > frontend/.env.local << EOF
# Frontend Environment Configuration
# Auto-generated by start-mobile.sh

# API Configuration - Use your machine's IP address for mobile access
NEXT_PUBLIC_API_URL=http://${HOST_IP}:8000
NEXT_PUBLIC_APP_NAME=Okuma Analizi

# Development Settings
NODE_ENV=development
NEXT_PUBLIC_DEBUG=false
EOF

echo "✅ .env.local güncellendi"
echo ""

# Docker servisleri yeniden başlat
echo "🔄 Docker servisleri yeniden başlatılıyor..."
export HOST_IP=$HOST_IP
docker-compose restart frontend api

echo ""
echo "✅ Sistem hazır!"
echo ""
echo "📱 Mobil cihazınızdan şu adreslere erişebilirsiniz:"
echo "   Frontend: http://${HOST_IP}:3000"
echo "   Backend:  http://${HOST_IP}:8000"
echo ""
echo "💡 Not: Mobil cihazınızın aynı WiFi ağında olduğundan emin olun!"
echo ""

